version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=polaris
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polaris
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

networks:
  app-network: