CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS employee_documents CASCADE;
DROP TABLE IF EXISTS leave_requests CASCADE;
DROP TABLE IF EXISTS salaries CASCADE;
DROP TABLE IF EXISTS attendances CASCADE;
DROP TABLE IF EXISTS subcategories CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS employee_profiles CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  permissions JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(30),
  bio TEXT,
  profile_photo TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  role_id BIGINT REFERENCES roles(id) ON DELETE RESTRICT,
  reset_password_token VARCHAR(255),
  reset_password_expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  slug VARCHAR(180) NOT NULL UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  description TEXT,
  category_images TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subcategories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  name VARCHAR(150) NOT NULL,
  making_charges NUMERIC(5,2) NOT NULL DEFAULT 0,
  material_loss NUMERIC(5,2) NOT NULL DEFAULT 0,
  subcategory_images TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(category_id, name)
);

CREATE TABLE employee_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) UNIQUE,
  full_name VARCHAR(255) NOT NULL,
  spouse_name VARCHAR(255),
  phone VARCHAR(30),
  mobile_number VARCHAR(30),
  alternative_mobile_number VARCHAR(30),
  emergency_contact_number VARCHAR(30),
  department VARCHAR(120) NOT NULL,
  designation VARCHAR(120) NOT NULL,
  date_of_joining DATE NOT NULL,
  date_of_birth DATE,
  date_of_exit DATE,
  date_of_releasing DATE,
  photo TEXT,
  employment_type VARCHAR(50) NOT NULL DEFAULT 'full_time',
  gender VARCHAR(30),
  marital_status VARCHAR(30),
  personal_email VARCHAR(255),
  blood_group VARCHAR(20),
  nationality VARCHAR(120),
  current_address TEXT,
  permanent_address TEXT,
  manager_name VARCHAR(255),
  probation_end_date DATE,
  bank_name VARCHAR(120),
  bank_account_number VARCHAR(100),
  ifsc_code VARCHAR(30),
  pan_number VARCHAR(30),
  aadhaar_number VARCHAR(30),
  passport_no VARCHAR(30),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  emergency_contact_name VARCHAR(255),
  emergency_contact_phone VARCHAR(30),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE attendances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL REFERENCES employee_profiles(code) ON DELETE CASCADE,
  attendance_date DATE NOT NULL,
  check_in_time TIME,
  check_out_time TIME,
  remarks TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (code, attendance_date)
);

CREATE TABLE salaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employee_profiles(id) ON DELETE CASCADE,
  effective_from DATE NOT NULL,
  basic_salary NUMERIC(12,2) NOT NULL,
  hra NUMERIC(12,2) NOT NULL DEFAULT 0,
  ta NUMERIC(12,2) NOT NULL DEFAULT 0,
  da NUMERIC(12,2) NOT NULL DEFAULT 0,
  special_allowance NUMERIC(12,2) NOT NULL DEFAULT 0,
  pf NUMERIC(12,2) NOT NULL DEFAULT 0,
  pf_number VARCHAR(50),
  esi NUMERIC(12,2) NOT NULL DEFAULT 0,
  esi_number VARCHAR(50),
  bonus_once_a_year NUMERIC(12,2) NOT NULL DEFAULT 0,
  advance_loan BOOLEAN NOT NULL DEFAULT FALSE,
  advance_money NUMERIC(12,2) NOT NULL DEFAULT 0,
  other_perks NUMERIC(12,2) NOT NULL DEFAULT 0,
  paid_leaves INTEGER NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  payment_frequency VARCHAR(30) NOT NULL DEFAULT 'monthly',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (employee_id, effective_from)
);

CREATE TABLE leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employee_profiles(id) ON DELETE CASCADE,
  leave_type VARCHAR(80) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMP WITH TIME ZONE,
  approver_notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employee_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employee_profiles(id) ON DELETE CASCADE,
  document_type VARCHAR(120),
  document_name VARCHAR(255),
  document_number VARCHAR(120),
  bank_account_number VARCHAR(100),
  ifsc_code VARCHAR(30),
  bank_name VARCHAR(120),
  nominee_relation VARCHAR(50),
  nominee_name VARCHAR(255),
  passbook_front_page_photo_url TEXT,
  pan_number VARCHAR(30),
  aadhaar_number VARCHAR(30),
  pan_document_url TEXT,
  aadhaar_document_url TEXT,
  esi_photo_url TEXT,
  uan_number VARCHAR(50),
  pf_account_number VARCHAR(50),
  issue_date DATE,
  expiry_date DATE,
  document_url TEXT,
  notes TEXT,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_attendances_code ON attendances(code);
CREATE INDEX idx_salaries_employee_id ON salaries(employee_id);
CREATE INDEX idx_leave_requests_employee_id ON leave_requests(employee_id);
CREATE INDEX idx_employee_documents_employee_id ON employee_documents(employee_id);
CREATE INDEX idx_subcategories_category_id ON subcategories(category_id);

INSERT INTO roles (name, description, permissions)
VALUES
  ('admin', 'System administrator with full access.', '{"*": true}'),
  ('hr', 'HR manager with employee data access.', '{"employees": ["read", "write"], "documents": ["read", "write"], "attendance": ["read", "write"], "salaries": ["read", "write"], "leaves": ["read", "write"]}'),
  ('user', 'Standard user with limited access.', '{"self": ["read", "write"]}')
ON CONFLICT (name)
DO UPDATE SET
  description = EXCLUDED.description,
  permissions = EXCLUDED.permissions,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO users (email, name, password_hash, phone, bio, profile_photo, is_active, role_id)
VALUES
  (
    'admin@admin.com',
    'Admin',
    crypt('admin', gen_salt('bf')),
    NULL,
    NULL,
    NULL,
    TRUE,
    (SELECT id FROM roles WHERE name = 'admin')
  )
ON CONFLICT (email)
DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = crypt('admin', gen_salt('bf')),
  phone = EXCLUDED.phone,
  bio = EXCLUDED.bio,
  profile_photo = EXCLUDED.profile_photo,
  is_active = EXCLUDED.is_active,
  role_id = EXCLUDED.role_id,
  updated_at = CURRENT_TIMESTAMP;

