BEGIN;

CREATE TABLE IF NOT EXISTS attendance_edit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_id BIGINT NOT NULL REFERENCES attendances(id) ON DELETE CASCADE,
  code VARCHAR(50) NOT NULL,
  attendance_date DATE NOT NULL,
  old_punch_in_time TIME,
  new_punch_in_time TIME,
  old_punch_out_time TIME,
  new_punch_out_time TIME,
  old_total_hours VARCHAR(20),
  new_total_hours VARCHAR(20),
  old_status VARCHAR(30),
  new_status VARCHAR(30),
  old_remarks TEXT,
  new_remarks TEXT,
  updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by_name VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_attendance_edit_logs_attendance_id
  ON attendance_edit_logs(attendance_id);

CREATE INDEX IF NOT EXISTS idx_attendance_edit_logs_code_date
  ON attendance_edit_logs(code, attendance_date);

COMMIT;
